# Generated by Django 4.2.16 on 2024-09-20 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    # 단독 설계도가 아닌 1번 설계도에 의도한 설계도임
    # 이게 있어야 연관이 있는 것. 번호가 연속된것은 상관없음
    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
